### ISSUE TITLE
Feature Request: Display type of root node

### ISSUE THREAD

**Issue by gregorwolf** [hschaefer123/cap-plantuml#1]
When looking right now at the root node in the rendered output it isn't clear what this node represents:

![Screenshot 2021-01-06 at 11 21 26](https://user-images.githubusercontent.com/2639535/103757649-58d5ba00-5011-11eb-820f-3586563711a4.png)

I would like to suggest to not completely remove the __metadata but instead use the information from __metadata.type:

```
{
  "d": {
    "__metadata": {
      "uri": "https://services.odata.org/V2/Northwind/Northwind.svc/Orders(10248)",
      "type": "NorthwindModel.Order"
    },
```

to fill the first entry of the JSON with:

```
 "**Order**": "",
```

That would produce this result:

![Screenshot 2021-01-06 at 11 29 57](https://user-images.githubusercontent.com/2639535/103758490-8d964100-5012-11eb-8966-95257a96ab99.png)

maybe also the child nodes could benefit from this.

**Comment by hschaefer123** [comment]
Hi Gregor,
thanks for the good idea.

I implemented it, but a little bit differently to be semantically more correct (in my opinion ;-)

![gw_fr1](https://user-images.githubusercontent.com/2110971/103926247-f36cf080-5118-11eb-8023-eada53b2ba06.png)

It was not that easy, because cap result filters out the initial _result for order.
Anyhow i got idea, to introduce the following to the demo:

![cap_calls](https://user-images.githubusercontent.com/2110971/103926523-53639700-5119-11eb-99de-75c82a2c8dd3.png)

I am using the underlying cloud sdk directly, to get a fresh axios full result (only for the __meta ;-)
But anyhow a good demo to see, how to easily make REST calls inside CAP using a destination.

Still waiting for feedback from Jhodel concerning
https://github.com/jcailan/cdse/issues/4
to create a comparisation, what-to-use-when, because cap currently does not support x-csrf-token on POST, but CDSE does!

Hope, the change is valueable for you.

Regards
Holger

**Comment by hschaefer123** [comment]
Should we close the issue?

**Comment by gregorwolf** [comment]
Like it very much. Thank you.
